# 模型配置文件
model:
  # ASR模型配置
  asr:
    # 选择中文语音识别模型
    model_name: "openai/whisper-large-v3"  # 支持中文的Whisper模型
    # model_name: "microsoft/DialoGPT-medium"  # 备选：支持对话的模型
    sample_rate: 16000
    max_length: 60  # 老年人说话较慢，增加最大长度
    pause_threshold_ms: 500  # 老年人停顿较多，增加阈值
    feature_dim: 1280  # Whisper-large的特征维度
    
    # 中文语音特定配置
    language: "zh"  # 中文
    task: "transcribe"  # 转录任务
    
    # 停顿检测配置
    vad_threshold: 0.5  # 语音活动检测阈值
    min_pause_duration: 0.3  # 最小停顿持续时间(秒)
    
    # 针对老年人语音的特殊配置
    elderly_specific:
      speech_rate_adjustment: 0.8  # 老年人语速较慢
      silence_tolerance: 1.0  # 容忍更长的静音
      accent_adaptation: true  # 方言适应
    
  # EEG处理配置  
  eeg:
    sample_rate: 250  # EEG采样率
    window_size: 4.0  # 窗口大小(秒)
    overlap: 0.5  # 重叠比例
    frequency_bands:
      delta: [0.5, 4]
      theta: [4, 8] 
      alpha: [8, 13]
      beta: [13, 30]
      gamma: [30, 100]
    feature_dim: 512
    
  # 概念瓶颈层配置
  concepts:
    # 语音概念
    speech_concepts:
      - name: "speech_rate"
        type: "continuous"
        range: [0.5, 4.0]  # 词/秒
        model_type: "linear"  # linear, mlp
        hidden_dims: [256, 128]
        
      - name: "pause_ratio"
        type: "continuous" 
        range: [0.0, 1.0]
        model_type: "linear"
        hidden_dims: [256, 128]
        
      - name: "lexical_richness"
        type: "continuous"
        range: [0.0, 1.0]  # TTR值
        model_type: "mlp"
        hidden_dims: [512, 256, 128]
        
      - name: "syntactic_complexity"
        type: "continuous"
        range: [1.0, 10.0]  # 平均句法树深度
        model_type: "mlp"
        hidden_dims: [512, 256, 128]
        
    # EEG概念
    eeg_concepts:
      - name: "alpha_power"
        type: "continuous"
        range: [0.0, 100.0]  # 功率谱密度
        model_type: "mlp"
        hidden_dims: [512, 256, 128]
        
      - name: "theta_beta_ratio"
        type: "continuous"
        range: [0.0, 10.0]
        model_type: "mlp"
        hidden_dims: [512, 256, 128]
        
      - name: "gamma_connectivity"
        type: "continuous"
        range: [0.0, 1.0]
        model_type: "mlp" 
        hidden_dims: [512, 256, 128]
    
    # 概念层训练参数
    concept_loss_weight: 1.0
    concept_regularization: 0.01
    
  # CRF分类器配置
  crf:
    algorithm: "lbfgs"
    c1: 0.1  # L1正则化
    c2: 0.1  # L2正则化
    max_iterations: 100
    num_classes: 3  # AD, MCI, Healthy
    class_names: ["Healthy", "MCI", "AD"]
    
  # 文本处理配置
  text:
    # 中文医学领域预训练模型
    model_name: "hfl/chinese-roberta-wwm-ext"  # 中文RoBERTa
    # model_name: "WENGSYX/ClinicalBERT-Chinese"  # 备选：中文医学BERT
    max_length: 512
    feature_dim: 768
    fine_tune: true
    
    # 中文文本特定配置
    language: "zh"
    tokenizer_type: "chinese"
    
    # 医学概念提取配置
    medical_concepts:
      enable_medical_ner: true  # 启用医学命名实体识别
      medical_vocab_path: "data/medical_terms_zh.txt"  # 中文医学词汇表
      
    # 针对老年人语言特点的配置
    elderly_language:
      dialect_support: true  # 支持方言
      repetition_detection: true  # 重复检测
      coherence_analysis: true  # 连贯性分析 